"""create tables

Revision ID: 9edca37270a3
Revises: 
Create Date: 2022-11-16 15:06:40.951222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9edca37270a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('algo_run_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=20), nullable=True),
    sa.Column('run', sa.Boolean(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_algo_run_config_id'), 'algo_run_config', ['id'], unique=False)
    op.create_table('power_algo_system',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('power', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_power_algo_system_id'), 'power_algo_system', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_power_algo_system_id'), table_name='power_algo_system')
    op.drop_table('power_algo_system')
    op.drop_index(op.f('ix_algo_run_config_id'), table_name='algo_run_config')
    op.drop_table('algo_run_config')
    # ### end Alembic commands ###
