"""time nullable column

Revision ID: 6a64ea0b4888
Revises: 0ab78960d787
Create Date: 2022-11-16 16:27:13.125443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a64ea0b4888'
down_revision = '0ab78960d787'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
